version: '1.0'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3003:3003
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    restart: always

volumes:
  redisdata:
